services:
  - type: worker
    name: click2steal-bot
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python bot.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
